### ISSUE TITLE
无法下线假人

### ISSUE THREAD

**Issue by yufengya0420** [YQ-LL-Plugins/LLSE-FakePlayer#24]
无法下线假人，但是假人依然在玩家列表内
![P 1)} { QE)~@(QDO R(UJI](https://user-images.githubusercontent.com/99462074/234849070-c212737b-979d-4a3c-9d95-5915bba2e9bf.png)
![3DE@KDM}M7Y1@TU7JWN00EN](https://user-images.githubusercontent.com/99462074/234849094-27cc5f26-6123-41e3-b7aa-426b5be716ee.png)

**Comment by yufengya0420** [comment]
假人不在假人列表里，在游戏内也看不见，但是在服务器在线玩家列表内能看见

**Comment by yufengya0420** [comment]
![F_HF_241XXI(@Y$5XMNVBDR](https://user-images.githubusercontent.com/99462074/234851833-fb3e6af4-6a6e-4a37-b385-1c1e4bac0933.png)

**Comment by yufengya0420** [comment]
我用机器人查服的时候，两个假人的名字还轮流显示，这两个假人我已经删除了，但是还随机显示在玩家在线列表里

**Comment by yqs112358** [comment]
最新版本经过测试无法复现，可能为旧版LL的bug。
如果后续还有出现无法删除的假人，请尝试进入plugin/LLSE-FakePlayer/fpdata和fpinventorys两个目录中删除指定名字的假人配置文件，然后重启BDS再看。

**Comment by yufengya0420** [comment]
> 最新版本经过测试无法复现，可能为旧版LL的bug。 如果后续还有出现无法删除的假人，请尝试进入plugin/LLSE-FakePlayer/fpdata和fpinventorys两个目录中删除指定名字的假人配置文件，然后重启BDS再看。

好的，大佬啥时候能更新一下容器内容预览

**Comment by yqs112358** [comment]
> > 最新版本经过测试无法复现，可能为旧版LL的bug。 如果后续还有出现无法删除的假人，请尝试进入plugin/LLSE-FakePlayer/fpdata和fpinventorys两个目录中删除指定名字的假人配置文件，然后重启BDS再看。
> 
> 好的，大佬啥时候能更新一下容器内容预览

我有空弄一下
