### ISSUE TITLE
为什么上线假人会导致服务器崩溃？

### ISSUE THREAD

**Issue by MoYili9** [YQ-LL-Plugins/LLSE-FakePlayer#30]
服主是傻瓜，服务器版本是1.20.1，使用的是最新核心
装有BehaviorLog，Advancements，LF_Music，CALL等LLSE
在服务器内使用/fpc gui创建假人之后，在假人列表里面，点击上线就会导致服务器直接崩溃，假人没有xuid
02:36:02 ERROR [LiteLoader] C++ Uncaught Exception Detected!
02:36:02 ERROR [LiteLoader] SEH_UNKNOW_ERROR
02:36:02 ERROR [LiteLoader] [failed to obtain stacktrace]
02:36:02 ERROR [LiteLoader] In API: McClass::spawnSimulatedPlayer
02:36:02 ERROR [LiteLoader] In Plugin: LLSE-FakePlayer
![407b05af3207e496](https://github.com/YQ-LL-Plugins/LLSE-FakePlayer/assets/139073709/8a009800-aa87-476b-9a4d-a2b4d9bd8c8d)
希望尽快得到解决

**Comment by yqs112358** [comment]
可能是旧版LL的适配问题？我这边目前1.20.3好像正常工作，升级一下服务端和LL试试
